### ISSUE TITLE
Source path with make switch only seems to work if in same directory

### ISSUE THREAD

**Issue by adhurwit** [Morgan-Stanley/morphir-elm#27]

**Comment by AttilaMihaly** [comment]
Thanks for reporting. Can you include the specific error you are getting?

**Comment by adhurwit** [comment]
Sorry, here it is: 

[Error: ENOENT: no such file or directory, open 'morphir.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'morphir.json'
}

**Comment by DamianReeves** [comment]
I've also experienced this (but forgot to file an issue).

**Comment by AttilaMihaly** [comment]
Ah, I get it now. It's confusing because the source directory and the location of `morphir.json` are different. I guess I should document that you need to run `morphir make` in the model project's root.

**Comment by DamianReeves** [comment]
I actually think as long as you allow the user to specify the path to `morphir.json` that we need to support executing properly from that location.

Also I think we shouldn't solve this by removing the ability to provide the `morphir.json` location.

**Comment by DamianReeves** [comment]
I can take a look at fixing this so that you can run it from wherever. If we agree that is the proper approach.

**Comment by AttilaMihaly** [comment]
Sorry, I was a bit confused. Now I remember that you can specify the project path and `morphir.json` is relative to that. The code looks good to me so it's possible that I just didn't push out the latest to NPM.

**Comment by adhurwit** [comment]
Not sure if my description was confusing. I was trying to do an automated build and use a full path to the morphir.json file, but it wouldn't follow the path and only work in same directory.

**Comment by AttilaMihaly** [comment]
I was confusing myself :)

Anyway, I pushed a new version to npm (`0.3.4`), that should fix it.

**Comment by AttilaMihaly** [comment]
Can any of you please confirm if this is fixed? My testing shows that it works as expected now.

**Comment by adhurwit** [comment]
I use"morphir-elm make src/Morphir/Sample/Apps/morphir.json" and it says "Could not find file at 'morphir.json'"

**Comment by AttilaMihaly** [comment]
Can you try `morphir-elm make -p src/Morphir/Sample/Apps` instead? The `-p` switch specifies the root directory of the project where it expects to find `morphir.json`.

**Comment by DamianReeves** [comment]
This appears have been fixed. Closing.
